# App for argoCD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yolo5-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shantalberkhof/K8sInfra.git'
    targetRevision: dev         # Points to the dev branch for Dev environment
    path: k8s/dev             # Correct path for Yolo5 manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev              # Syncing to the 'dev' namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

