apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-polybot
  labels:
    app: app-polybot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-polybot
  template:
    metadata:
        labels:
          app: app-polybot
    spec:
      containers:
      - name: app-polybot
        image: shantalberkhof/my_polybot_k8s:v2
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1000Mi
        ports:
          - containerPort: 8443
        env:
          - name: polybot-service
            value: http://polybot-service:8443
          - name: REGION_NAME
            value: "us-east-2"
          - name: DYNAMODB_TABLE
            value: "shantal-dynamoDB-aws-dev"
          - name: SQS_QUEUE_NAME
            value: "https://sqs.us-east-2.amazonaws.com/019273956931/shantal-queue-aws"
          - name: BUCKET_NAME
            value: "shantal-awsproject-dev"
          - name: TELEGRAM_APP_URL
            value: "https://bot.domain.shantal.k8s.int-devops.click"
          - name: TELEGRAM_TOKEN_NAME
            value: "shantal-telegram-bot-token"

---
apiVersion: v1
kind: Service # Object of service -> can wrap the pods with the same label. So Polybot knows the address of Yolo5.
metadata:
  name: polybot-service # The DNS address to polybot pod
spec:
  selector:
    app: app-polybot # This is the name of the label (match the label in the deployment)
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443