apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-polybot
  namespace: dev  # Specify the namespace
  labels:
    app: app-polybot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-polybot
  template:
    metadata:
        labels:
          app: app-polybot
    spec:
      containers:
      - name: app-polybot
        image: shantalberkhof/my_polybot_k8s_dev:v2
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1000Mi
        ports:
          - containerPort: 8443
        env:
#          - name: polybot-service
#            value: http://polybot-service:8443
          - name: REGION_NAME
            value: "us-east-2"
          - name: DYNAMODB_TABLE
            value: "shantal-dynamoDB-aws-dev"
          - name: SQS_QUEUE_NAME
            value: "shantal-queue-aws-dev"
          - name: BUCKET_NAME
            value: "shantal-awsproject-dev"
          - name: TELEGRAM_APP_URL
            value: "https://bot.domain.shantal.k8s.dev.int-devops.click"
          - name: TELEGRAM_TOKEN_NAME
            value: "shantal-telegram-bot-token-dev"
          - name: ALB_URL #Network load balancer in this case
            value: "a27540a9f786c44818f1a2bff39d3ee8-499d87062077720f.elb.us-east-2.amazonaws.com"
          - name: PUBLIC_KEY_VALUE
            value: "shantal-YOURPUBLICpem-dev"


---
apiVersion: v1
kind: Service # Object of service -> can wrap the pods with the same label. So Polybot knows the address of Yolo5.
metadata:
  name: polybot-service # The DNS address to polybot pod
  namespace: dev  # Specify the namespace
spec:
  selector:
    app: app-polybot # This is the name of the label (match the label in the deployment)
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443