apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polybot-ingress-prod
  namespace: prod
spec:
  tls:
    - hosts:
        - bot.domain.shantal.k8s.int-devops.click
      secretName: tls-secret
  ingressClassName: nginx
  rules:
    - host: bot.domain.shantal.k8s.int-devops.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: polybot-service
                port:
                  number: 8443

#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: polybot-ingress-prod
#  namespace: prod
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  rules:
#    - host: bot.domain.shantal.k8s.int-devops.click  # Replace with your subdomain
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: polybot-service
#                port:
#                  number: 8443
