apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polybot-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/shantalberkhof/K8sInfra.git'
    targetRevision: dev
    path: 'K8sInfra/k8s/Polybot'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
