apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-yolo5
  labels:
    app: app-yolo5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-yolo5
  template:
    metadata:
        labels:
          app: app-yolo5
    spec:
      containers:
      - name: server
        image: shantalberkhof/my_yolo5_k8s_dev:v2
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1000Mi
        env:
          - name: yolo5-service
            value: http://yolo5-service:3000
          - name: REGION_NAME
            value: "us-east-2"
          - name: BUCKET_NAME
            value: "shantal-awsproject-dev"
          - name: DYNAMODB_TABLE
            value: "shantal-dynamoDB-aws-dev"
          - name: SQS_QUEUE_NAME
            value: "shantal-queue-aws-dev"
          - name: ALB_URL #Network load balancer in this case
            value: "a35eb43ed844242b5b0af4bd1b1219b5-7a6a47f2a25e90e1.elb.us-east-2.amazonaws.com"


---
apiVersion: v1
kind: Service
metadata:
  name: yolo5-service # The DNS address to yolo5 pod
spec:
  selector:
    app: app-yolo5 # This is the name of the label (match the label in the deployment)
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler # Horizontal Pod Autoscaler (HPA)
metadata:
  name: yolo5-hpa
  namespace: default  # Changed to "default" or apply to the correct namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-yolo5  # Match the deployment name
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
