apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-yolo5
  namespace: dev  # Specify the namespace
  labels:
    app: app-yolo5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-yolo5
  template:
    metadata:
      labels:
        app: app-yolo5
    spec:
      containers:
      - name: app-yolo5
        image: shantalberkhof/my_yolo5_k8s_dev:v2
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1000Mi
        ports:
          - containerPort: 8080
        env:
#          - name: yolo5-service
#            value: http://yolo5-service:3000
          - name: REGION_NAME
            value: "us-east-2"
          - name: BUCKET_NAME
            value: "shantal-awsproject-dev"
          - name: DYNAMODB_TABLE
            value: "shantal-dynamoDB-aws-dev"
          - name: SQS_QUEUE_NAME
            value: "shantal-queue-aws-dev"
          - name: ALB_URL #Network load balancer in this case
            value: "a08e794fe1fad4bf59f23aa4f36a5b96-037b5809b1deba3c.elb.us-east-2.amazonaws.com"

---

apiVersion: v1
kind: Service
metadata:
  name: yolo5-service # The DNS address to yolo5 pod
  namespace: dev  # Specify the namespace
spec:
  selector:
    app: app-yolo5 # This is the name of the label (match the label in the deployment)
  ports:
    - protocol: TCP
      port: 8080 # Edit from 3000
      targetPort: 8080

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler # Horizontal Pod Autoscaler (HPA)
metadata:
  name: yolo5-hpa
  namespace: dev  # Specify the namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-yolo5  # Match the deployment name
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50