apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yolo5-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/K8sInfra.git'
    targetRevision: HEAD
    path: k8s/Yolo5
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
