name: CI/CD for Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0'

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f ./k8s/polybot/dev/
          kubectl apply -f ./k8s/yolo/dev/