name: CI/CD for Prod

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          # Run your tests here, e.g., unit tests, integration tests
          echo "Running tests..."

      - name: Merge to Main
        if: success()
        run: git merge dev

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0'

      - name: Apply Kubernetes Manifests to Prod
        run: |
          kubectl apply -f ./k8s/polybot/prod/
          kubectl apply -f ./k8s/yolo/prod/
